[package]
name = "xray-export"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
xray-error = { workspace = true }
xray-typescript = { workspace = true }

[lints]
workspace = true
