[package]
name = "xray-archive"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bounded_join_set = "0.3.0"
byteorder = { workspace = true }
crc32fast = "1.5.0"
delharc = { workspace = true, features = ["std", "lh1"] }
log = { workspace = true }
minilzo-rs = "0.6.1"
regex = { workspace = true }
serde = { workspace = true }
walkdir = { workspace = true }
xray-error = { workspace = true }
xray-utils = { workspace = true }

[lints]
workspace = true
