[package]
name = "xray-gamedata"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.1", features = ["display"] }
ddsfile = "0.5.2"
log = "0.4.33"
rayon = "1.12.0"
regex = "1.13.1"
uuid = { version = "1.24.0", features = ["v4"] }
walkdir = "2.5.0"
xray-db = { path = "../xray-db" }
xray-error = { path = "../xray-error" }
xray-ltx = { path = "../xray-ltx" }
xray-lua = { path = "../xray-lua" }
xray-output = { path = "../xray-output" }
xray-report = { path = "../xray-report" }
xray-assets = { path = "../xray-assets" }
xray-shaders = { path = "../xray-shaders" }
xray-sound = { path = "../xray-sound" }
xray-utils = { path = "../xray-utils" }

[dev-dependencies]
xray-chunk = { path = "../xray-chunk" }

[lints]
workspace = true
