[package]
name = "xray-gamedata"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["display"] }
ddsfile = { workspace = true }
rayon = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
walkdir = { workspace = true }
xray-db = { workspace = true }
xray-error = { workspace = true }
xray-ltx = { workspace = true }
xray-lua = { workspace = true }
xray-output = { workspace = true }
xray-report = { workspace = true }
xray-assets = { workspace = true }
xray-shaders = { workspace = true }
xray-sound = { workspace = true }
xray-utils = { workspace = true }
xray-xml = { workspace = true }

[dev-dependencies]
xray-chunk = { workspace = true }

[lints]
workspace = true
