[package]
name = "xray-texture"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
ddsfile = { workspace = true }
image = { workspace = true, features = [
  "rayon", "bmp", "dds", "exr", "ff", "gif", "hdr", "ico", "jpeg", "png", "pnm", "qoi", "tga", "tiff", "webp",
] }
image_dds = "0.7.2"
log = { workspace = true }
path-absolutize = "4.0.1"
rayon = { workspace = true }
roxmltree = "0.21.1"
serde = { workspace = true }
xray-error = { workspace = true }
xray-ltx = { workspace = true }
xray-output = { workspace = true }
xray-utils = { workspace = true }

[lints]
workspace = true
