/// Asset category inferred from an X-Ray logical path's extension or recognized suffix.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum XrayAssetType {
  Ai,
  Anm,
  CForm,
  Dds,
  Dm,
  Efd,
  EnvMod,
  FogVol,
  Game,
  Geom,
  GeomX,
  Hom,
  Ini,
  Level,
  Lights,
  Ltx,
  Misc,
  Ogf,
  Ogg,
  Ogm,
  Omf,
  Ppe,
  PsStatic,
  SndStatic,
  Script,
  Seq,
  Shader,
  Spawn,
  Thm,
  Wallmarks,
  Details,
  XrPack,
}

impl XrayAssetType {
  pub(crate) fn from_logical_path(path: &str) -> Option<Self> {
    match path.rsplit_once('.').map(|(_, extension)| extension) {
      Some("ai") => Some(Self::Ai),
      Some("anm" | "anm1") => Some(Self::Anm),
      Some("cform") => Some(Self::CForm),
      Some("dds") => Some(Self::Dds),
      Some("details") => Some(Self::Details),
      Some("dm") => Some(Self::Dm),
      Some("efd") => Some(Self::Efd),
      Some("env_mod") => Some(Self::EnvMod),
      Some("fog_vol") => Some(Self::FogVol),
      Some("game") => Some(Self::Game),
      Some("geom") => Some(Self::Geom),
      Some("geomx") => Some(Self::GeomX),
      Some("hom") => Some(Self::Hom),
      Some("ini") => Some(Self::Ini),
      Some("lights") => Some(Self::Lights),
      Some("log" | "bat" | "py" | "cmd") => Some(Self::Misc),
      Some("ltx") => Some(Self::Ltx),
      Some("ogf") => Some(Self::Ogf),
      Some("ogg") => Some(Self::Ogg),
      Some("ogm") => Some(Self::Ogm),
      Some("omf") => Some(Self::Omf),
      Some("ppe") => Some(Self::Ppe),
      Some("ps" | "s" | "s_" | "h" | "vs" | "cs" | "hs" | "ds" | "gs") => Some(Self::Shader),
      Some("ps_static") => Some(Self::PsStatic),
      Some("script") => Some(Self::Script),
      Some("seq" | "seq_") => Some(Self::Seq),
      Some("snd_static") => Some(Self::SndStatic),
      Some("spawn") => Some(Self::Spawn),
      Some("thm") => Some(Self::Thm),
      Some("wallmarks") => Some(Self::Wallmarks),
      Some("xr") => Some(Self::XrPack),
      _ if path.ends_with("level") => Some(Self::Level),
      _ if path.ends_with(".s") => Some(Self::Shader),
      _ => None,
    }
  }
}
