name: Build and test windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - uses: dtolnay/rust-toolchain@stable

      - name: Configure Git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: bin/xrf-ui/package.json
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: bin/xrf-ui/pnpm-lock.yaml

      - uses: Swatinem/rust-cache@v2

      - uses: mozilla-actions/sccache-action@v0.0.10

      - name: Enable sccache
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $env:GITHUB_ENV
          echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $env:GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $env:GITHUB_ENV

      - name: Run formatter
        run: cargo fmt --all -- --check

      - name: Run xray workspace tests
        run: cargo test --verbose --workspace --lib

      - name: Build CLI
        run: cargo build -p xrf-cli --release --locked

      - name: Upload CLI build artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: xrf-cli
          path: target/release/xrf-cli.exe
          retention-days: 1

      - name: Install UI dependencies
        run: pnpm.cmd --dir bin/xrf-ui install --frozen-lockfile

      - name: Build UI
        run: pnpm.cmd --dir bin/xrf-ui build

      - name: Build application
        working-directory: bin/xrf-app
        run: ..\xrf-ui\node_modules\.bin\tauri.cmd build --ci --no-bundle --config tauri.ci.conf.json

      - name: Upload application build artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: xrf-app
          path: target/release/xrf-app.exe
          retention-days: 1

      - name: Show sccache stats
        if: always()
        run: sccache --show-stats


  upload-nightly:
    if: ${{ github.ref_name == 'main' && github.event_name != 'pull_request' }}
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Update nightly tag
        uses: EndBug/latest-tag@latest
        id: update-nightly-tag
        with:
          ref: nightly

      - uses: actions/download-artifact@v8
        with:
          name: xrf-cli

      - name: Publish nightly cli build
        if: ${{ steps.update-nightly-tag.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber nightly xrf-cli.exe

      - uses: actions/download-artifact@v8
        with:
          name: xrf-app

      - name: Publish nightly application build
        if: ${{ steps.update-nightly-tag.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber nightly xrf-app.exe
